/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "opamp_1.h"
#include "MIC_aliases.h"
#include "MIC.h"
#include "AMux_1.h"
#include "SW_src_aliases.h"
#include "SW_src.h"
#include "PWM_R.h"
#include "PWM_G.h"
#include "PWM_B.h"
#include "PWM_clk.h"
#include "Pin_R_aliases.h"
#include "Pin_R.h"
#include "Pin_G_aliases.h"
#include "Pin_G.h"
#include "Pin_B_aliases.h"
#include "Pin_B.h"
#include "LIN_aliases.h"
#include "LIN.h"
#include "SW_mode_aliases.h"
#include "SW_mode.h"
#include "LIN_AMP_OUT_aliases.h"
#include "LIN_AMP_OUT.h"
#include "Timer_1.h"
#include "isr_Timer.h"
#include "ADC.h"
#include "isr_ADC.h"
#include "timer_clock.h"
#include "OnboardLED_aliases.h"
#include "OnboardLED.h"
#include "LED_JACK_aliases.h"
#include "LED_JACK.h"
#include "LED_MIC_aliases.h"
#include "LED_MIC.h"
#include "UART.h"
#include "EEPROM.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

